version: '3.8'

volumes:
  mysql-data:

services:
  web:
    image: nginx:1.18
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
  db:
    image: mysql:5.7
    ports:
      - '4306:3306'
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-data:/var/lib/mysql
  db_test:
    image: mysql:5.7
    ports:
      - '4307:3306'
    environment:
      MYSQL_DATABASE: docker_db_test
      MYSQL_USER: docker_user_test
      MYSQL_PASSWORD: docker_pass_test
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql